discord_token: abc.def.ghi
irc_server: localhost:6697
guild_id: 315277951597936640
nickserv_identify: password123

# Updating this will automatically add or remove puppets from channels
channel_mappings:
  "#bottest chanKey": 316038111811600387
  "#bottest2": 318327329044561920

suffix: "_d2"
separator: "_"
irc_listener_name: "_d2"
webirc_pass: abcdef.ghijk.lmnop

# You definitely should restart the bridge after changing these:
insecure: true
no_tls: false
debug: false
webhook_prefix: "(auto-test)"
cooldown_duration: 86400 # optional, default 86400 (24 hours), time in seconds for a discord user to be offline before it's puppet disconnects from irc
#simple: true # this requires restart
